In [624]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [625]:
# 엑셀파일 읽어들이기
df = pd.read_excel('../data/야인시대 1부 (1~50) 통합대본.xlsx')
df2 = pd.read_excel('../data/야인시대 2부(51~124) 통합대본.xlsx')
df= pd.concat([df, df2], axis=0)

In [626]:
# 인물 컬럼에서 "#"으로 시작하는 행은 제거하는 코드 
df = df[df["인물"].str.startswith("#") == False]

In [627]:
people=list(df["인물"].value_counts()[:50].index) # 대사가 많은 인물만 추리기 


# 두한, 청년두한, 소년두한
# 정진영, 청년진영 
# 개코, 소년개코 
# 해당 인물을 같은 라벨로 표시하기 : replace사용
replace_dict = {
    "청년두한": "두한",
    "소년두한": "두한",
    "청년진영": "정진영",
    "청년개코": "개코"
}

df["인물"] = df["인물"].replace(replace_dict)
df["인물"].value_counts()[:50]

인물
두한      5677
이정재     2158
김영태     1803
임화수     1492
정진영     1314
최동열     1141
개코      1040
김무옥      966
미와       943
문영철      861
시라소니     828
하야시      687
조병옥      659
곽영주      653
이기붕      618
신영균      611
유지광      594
이승만      585
김기홍      584
유진산      583
나레이션     536
이화룡      534
삼수       497
나미꼬      474
구마적      471
이석재      455
원노인      442
눈물       439
설향       342
김관철      341
친할머니     341
쌍칼       337
번개       335
정대발      333
애란       294
오숙근      293
김동진      289
김천호      284
이억일      276
정팔       272
한백수      272
장택상      268
이영숙      266
소년개코     265
왕발       258
마루오까     253
조열승      228
박인애      227
오무라      227
와싱턴      225
Name: count, dtype: int64

In [628]:
# 긴 문장만 남기기

df = df[df["대사"].str.len() > 25]

In [629]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29369 entries, 2 to 35723
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   회차      29369 non-null  int64 
 1   시간      29369 non-null  object
 2   인물      29369 non-null  object
 3   대사      29369 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.1+ MB


In [630]:
import re

def extract_korean_words(text):
    korean_words = re.findall(r"[가-힣]+", text)
    return ' '.join(korean_words)

# "대사" 열에 함수 적용하여 추출된 한글 단어들을 공백으로 구분하여 하나의 문자열로 변환하여 저장
df["대사"] = df["대사"].apply(extract_korean_words)

print(df)

        회차     시간    인물                                                 대사
2        1    0~5  나레이션  이 이야기는 암울했던 민족의 수난기와 격동기의 역사를 살다 갔던 영원한 야인 김두한...
3        1    0~5  나레이션  그러나 드라마의 원만한 진행을 위하여 시대와 역사적 상황을 운영하는 인물 일부분에서...
7        1    0~5   최동열                     으응 너무 늦었어 요즘 통 날씨가 좋지 않아서 미뤘더니
9        1    0~5   최동열  흐흐흐 흙이 좋은 것이겠지 정치를 그만 두겠다고 했던가 국회의원이 정치를 그만두면 ...
11       1    0~5   최동열                    별장 자네가 무슨 별장이 허 허허허 혹시 교도소 얘기인가
...    ...    ...   ...                                                ...
35718  124  55~60  나레이션  많은 인파가 몰린 그의 장례 행렬에는 한 무리의 어린 아이들도 그 뒤를 잇고 있었다...
35720  124  60~65  나레이션  김두한 그는 일제 말 우리가 주권을 잃었던 식민지 시절부터 해방 이후 좌우익의 대립...
35721  124  60~65   최동열  나는 오랫동안 자네를 지켜보아 온 사람일세 자네는 자네답게 살았어 조선의 주먹 황제...
35722  124  60~65   최동열  나름대로 자네의 역사를 가지고 자네의 시대를 치열하고 열심히 살았다는 얘기야 뭐랄까...
35723  124  60~65  나레이션  야인시대 그렇다 그것은 바로 그가 몸바쳐 살아왔던 이 나라 격동기의 또 다른 역사의...

[29369 rows x 4 columns]


In [631]:
df["대사"]

2        이 이야기는 암울했던 민족의 수난기와 격동기의 역사를 살다 갔던 영원한 야인 김두한...
3        그러나 드라마의 원만한 진행을 위하여 시대와 역사적 상황을 운영하는 인물 일부분에서...
7                           으응 너무 늦었어 요즘 통 날씨가 좋지 않아서 미뤘더니
9        흐흐흐 흙이 좋은 것이겠지 정치를 그만 두겠다고 했던가 국회의원이 정치를 그만두면 ...
11                         별장 자네가 무슨 별장이 허 허허허 혹시 교도소 얘기인가
                               ...                        
35718    많은 인파가 몰린 그의 장례 행렬에는 한 무리의 어린 아이들도 그 뒤를 잇고 있었다...
35720    김두한 그는 일제 말 우리가 주권을 잃었던 식민지 시절부터 해방 이후 좌우익의 대립...
35721    나는 오랫동안 자네를 지켜보아 온 사람일세 자네는 자네답게 살았어 조선의 주먹 황제...
35722    나름대로 자네의 역사를 가지고 자네의 시대를 치열하고 열심히 살았다는 얘기야 뭐랄까...
35723    야인시대 그렇다 그것은 바로 그가 몸바쳐 살아왔던 이 나라 격동기의 또 다른 역사의...
Name: 대사, Length: 29369, dtype: object

In [632]:
people=['두한',
 '이정재',
 '정진영',
 '이승만'
]
df=df[df["인물"].isin(people)].reset_index(drop=True)
df.to_csv('../data/야인시대.csv', index=False)

In [633]:
label = df["인물"]
feature = df["대사"]

In [634]:
# label 을 인코딩하기
from sklearn.preprocessing import LabelEncoder
print(df["인물"].unique())
encoder = LabelEncoder()
encoder.fit(label)
label = encoder.transform(label)
df["인물"]=label
df["인물"].unique()

['두한' '정진영' '이정재' '이승만']


array([0, 3, 2, 1])

In [635]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, corpus):
        nsmcDF = pd.DataFrame(corpus).fillna('')

        x_data = nsmcDF['대사'].values
        self.x_data = x_data
        self.y_data = nsmcDF['인물'].values

    def __len__(self):
        return len(self.x_data)

    def __getitem__(self, idx):
        x = self.x_data[idx]
        y = self.y_data[idx]
        return y, x

In [636]:
trainDS = CustomDataset(df)

In [637]:
len(trainDS)

5120

In [638]:
### ===> 토큰관련 특별 문자
UNK = '<UNK>'
PAD = '<PAD>'

In [639]:
from konlpy.tag import Komoran,Okt
from collections import Counter
from torchtext.vocab import build_vocab_from_iterator

In [640]:
### 토큰화 인스턴스 생성
tokenizer =Okt()

Exception: Install MeCab in order to use it: http://konlpy.org/en/latest/install/

In [ ]:
def yield_tokens(data_iter):
    for label, text in data_iter:
        yield (token for token in tokenizer.morphs(text) if len(token) >= 1) 

In [ ]:
VOCAB = build_vocab_from_iterator( yield_tokens(trainDS), min_freq=2, specials= [PAD, UNK],special_first=True)
VOCAB.set_default_index(VOCAB[UNK])

In [ ]:
### VOCAB 메서드 
VOCAB.get_itos()[:9],  VOCAB.get_stoi()[UNK]

(['<PAD>', '<UNK>', '이', '을', '들', '가', '에', '은', '를'], 1)

In [ ]:
VOCAB.get_itos()[:100]

['<PAD>',
 '<UNK>',
 '이',
 '을',
 '들',
 '가',
 '에',
 '은',
 '를',
 '말',
 '는',
 '이야',
 '한',
 '그',
 '도',
 '아',
 '것',
 '의',
 '내',
 '우리',
 '거',
 '다',
 '사람',
 '입니다',
 '거야',
 '일',
 '나',
 '할',
 '해',
 '으로',
 '야',
 '잘',
 '그래',
 '게',
 '안',
 '두',
 '지금',
 '고',
 '저',
 '하고',
 '하는',
 '일이',
 '에서',
 '생각',
 '뭐',
 '하',
 '그렇게',
 '수',
 '못',
 '로',
 '좀',
 '그리고',
 '과',
 '형님',
 '서',
 '김두한',
 '요',
 '하하',
 '있는',
 '겁니다',
 '만',
 '난',
 '니까',
 '어떻게',
 '그런',
 '정말',
 '제',
 '더',
 '무슨',
 '놈',
 '알',
 '예',
 '와',
 '이제',
 '왜',
 '자',
 '적',
 '까지',
 '나라',
 '때',
 '너',
 '님',
 '전',
 '이렇게',
 '에게',
 '아니',
 '이오',
 '하지만',
 '있어',
 '봐',
 '오늘',
 '얘기',
 '있습니다',
 '친구',
 '하지',
 '여기',
 '위해',
 '건',
 '이다',
 '당신']

In [ ]:
### ===> 텍스트 >>>> 정수 인코딩
text_pipeline = lambda x: VOCAB(tokenizer.morphs(x))

### ===> 레이틀 >>> 정수 인코딩 (0~3)
label_pipeline = lambda x: int(x)

In [ ]:
### 인코딩 : 문자 >>>> 숫자로 변환
token_to_id ={ label : id  for label, id in VOCAB.get_stoi().items()}

### 디코딩 : 숫자 >>>> 문자로 변환
id_to_token ={ id : label  for label, id in VOCAB.get_stoi().items()}

In [ ]:
### ===> 모듈로딩
from torch.utils.data import DataLoader
from torch.utils.data.dataset import random_split
from torch.nn.utils.rnn import pad_sequence
import torch  

In [ ]:
### ===> 실행 디바이스 설정
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
def collate_batch(batch):
    label_list, text_list, offsets = [], [], [0]
    for (_label, _text) in batch:
        label_list.append(label_pipeline(_label))
        processed_text = torch.tensor(text_pipeline(_text), dtype=torch.int64)
        text_list.append(processed_text)
        offsets.append(processed_text.size(0))
    label_list = torch.tensor(label_list, dtype=torch.int64)
    offsets = torch.tensor(offsets[:-1]).cumsum(dim=0)
    text_list = torch.cat(text_list)
    
    return label_list.to(device), text_list.to(device), offsets.to(device)

In [ ]:
BATCH_SIZE = 32
num_train = int(len(trainDS) * 0.90)
print(f' num_train :{num_train}')

split_trainDS, split_validDS= random_split( trainDS, [num_train, len(trainDS) - num_train])
print(f' len(split_trainDS) :{len(split_trainDS)}')
print(f' len(split_validDS) :{len(split_validDS)}')

trainDL = DataLoader( split_trainDS, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_batch )
validDL = DataLoader( split_validDS, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_batch )

 num_train :4864
 len(split_trainDS) :4864
 len(split_validDS) :256


In [ ]:
trainDS

In [ ]:
print(f' len(trainDL) :{len(trainDL)*BATCH_SIZE}')
print(f' len(validDL) :{len(validDL)*BATCH_SIZE}')

 len(trainDL) :4864
 len(validDL) :256


In [ ]:
for i in trainDL:
    print(i)
    break

(tensor([2, 0, 0, 2, 0, 0, 2, 0, 1, 0, 0, 2, 2, 0, 0, 0, 1, 0, 3, 2, 3, 2, 2, 0,
        3, 0, 2, 2, 0, 2, 0, 1]), tensor([   2,   20, 4409,  325,  279, 1585,  153,  371,  324,  375, 2562,   22,
           4,    7,  213,  225, 4369, 1232,  101,  941,  123,  202,   18,    5,
         150,    3,  590,    1,    1,   36,    2,   78,    5,   63,    1,   25,
         324,   69,    4,   84,    1,   22,    3,  321,   53,   29, 4272,   47,
          10,  142,  900,  502,   76,    7,  294,  379,    1,  900,   38,   14,
         792,   18,  558,   23,  372,   77,  412,   27,   47, 1407, 1320,  149,
          31,  664,   21,   51,  147,  131,    8,   20, 1970,   58,  374,  395,
          23,   83,    4,  513,   18,    5, 2844, 2759, 1009,  828,  887,  172,
         127, 1104, 4072,  887,  172,  127,   56,    1,    1,    1,  311,    2,
        5120,  963,  151,  913,  245,  757,   17,  259,   52, 3380, 3533,  115,
          60,   12,  116,    6, 5011, 1809,   28,   13,  173,   42,  155, 1390,
     

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

class TextModel(nn.Module):
    def __init__(self, VOCAB_SIZE, EMBEDD_DIM, HIDDEN_SIZE, NUM_CLASS):
        super(TextModel, self).__init__()
        self.embedding = nn.EmbeddingBag(VOCAB_SIZE, EMBEDD_DIM, sparse=False)
        self.hidden = nn.Linear(EMBEDD_DIM, HIDDEN_SIZE)
        self.fc = nn.Linear(HIDDEN_SIZE, NUM_CLASS)
        self.init_weights()
    
    def init_weights(self):
        initrange = 0.5
        self.embedding.weight.data.uniform_(-initrange, initrange)
        self.hidden.weight.data.uniform_(-initrange, initrange)
        self.fc.weight.data.uniform_(-initrange, initrange)
        self.fc.bias.data.zero_()
    
    def forward(self, text, offsets):
        embedded = self.embedding(text, offsets)
        hidden_output = F.relu(self.hidden(embedded))
        output = self.fc(hidden_output)
        return output

In [ ]:
# 학습 관련 파라미터와 인스턴스 
HIDDEN_SIZE=16
EMBEDD_DIM=64
VOCAB_SIZE = len(VOCAB)
NUM_CLASS = 4
EPOCHS = 10
LR = 0.1
BATCH_SIZE = 64

In [ ]:
# 학습 관련 인스턴스
import torch.optim as optim
MODEL = TextModel(VOCAB_SIZE, EMBEDD_DIM, HIDDEN_SIZE, NUM_CLASS).to(device)
CRITERION = nn.CrossEntropyLoss()
OPTIMIZER = optim.AdamW(MODEL.parameters(), lr=LR)
SCHEDULER = optim.lr_scheduler.StepLR(OPTIMIZER, 1.0, gamma=0.1) # learning rate를 줄이는 용도 

In [ ]:
from tqdm import tqdm

def train(model, dataloader, optimizer, criterion, epoch):
    
    model.train()
    total_acc, total_count = 0,0
    log_interval=100
    pbar = tqdm(enumerate(dataloader), total=len(dataloader))
    
    for idx, (label, text, offsets) in pbar:
        predicted_label = model(text, offsets)
        optimizer.zero_grad()
        loss = criterion(predicted_label, label)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.1)
        optimizer.step()
        total_acc += (predicted_label.argmax(1) == label).sum().item()
        total_count += label.size(0)
        
        if idx % log_interval == 0 and idx > 0:
            print(f"epoch : {epoch} batch : {idx} loss : {loss.item()}")
            print(f"Accuracy : {total_acc/total_count}")
            total_acc, total_count = 0,0
            

In [ ]:
def evaluate(model, dataloader, criterion):
    model.eval()
    
    total_acc, total_count = 0,0
    
    with torch.no_grad():
        for idx, (label, text, offsets) in enumerate(dataloader):
            predicted_label = model(text, offsets)
            loss = criterion(predicted_label, label)
            total_acc += (predicted_label.argmax(1) == label).sum().item()
            total_count += label.size(0)
            
    return total_acc/total_count

In [ ]:
# 학습 진행
for epoch in range(1, EPOCHS+1):
    train(MODEL, trainDL, OPTIMIZER, CRITERION, epoch)
    accu_val = evaluate(MODEL, validDL, CRITERION)
    print(f"epoch : {epoch} Accuracy : {accu_val}")
    #SCHEDULER.step()
torch.save(MODEL, "model.pth")

 66%|██████▋   | 101/152 [00:11<00:05,  9.38it/s]

epoch : 1 batch : 100 loss : 0.6878868937492371
Accuracy : 0.5659034653465347


100%|██████████| 152/152 [00:16<00:00,  9.30it/s]


epoch : 1 Accuracy : 0.5625


 67%|██████▋   | 102/152 [00:10<00:05,  9.33it/s]

epoch : 2 batch : 100 loss : 0.7305158376693726
Accuracy : 0.75


100%|██████████| 152/152 [00:16<00:00,  9.40it/s]


epoch : 2 Accuracy : 0.64453125


 66%|██████▋   | 101/152 [00:10<00:04, 10.83it/s]

epoch : 3 batch : 100 loss : 0.5382252931594849
Accuracy : 0.7920792079207921


100%|██████████| 152/152 [00:16<00:00,  9.42it/s]


epoch : 3 Accuracy : 0.6953125


 67%|██████▋   | 102/152 [00:10<00:05,  9.60it/s]

epoch : 4 batch : 100 loss : 1.0720224380493164
Accuracy : 0.8168316831683168


100%|██████████| 152/152 [00:16<00:00,  9.42it/s]


epoch : 4 Accuracy : 0.6484375


 68%|██████▊   | 104/152 [00:10<00:04, 11.38it/s]

epoch : 5 batch : 100 loss : 0.28500455617904663
Accuracy : 0.8301361386138614


100%|██████████| 152/152 [00:16<00:00,  9.34it/s]


epoch : 5 Accuracy : 0.671875


 66%|██████▌   | 100/152 [00:10<00:05,  9.39it/s]

epoch : 6 batch : 100 loss : 0.4856991767883301
Accuracy : 0.8412747524752475


100%|██████████| 152/152 [00:16<00:00,  9.28it/s]


epoch : 6 Accuracy : 0.6328125


 66%|██████▌   | 100/152 [00:10<00:05,  9.48it/s]

epoch : 7 batch : 100 loss : 1.0423462390899658
Accuracy : 0.8084777227722773


100%|██████████| 152/152 [00:16<00:00,  9.47it/s]


epoch : 7 Accuracy : 0.640625


 67%|██████▋   | 102/152 [00:10<00:05,  9.42it/s]

epoch : 8 batch : 100 loss : 0.4712865650653839
Accuracy : 0.8567450495049505


100%|██████████| 152/152 [00:15<00:00,  9.60it/s]


epoch : 8 Accuracy : 0.65625


 68%|██████▊   | 103/152 [00:10<00:04, 10.44it/s]

epoch : 9 batch : 100 loss : 0.8515774011611938
Accuracy : 0.8452970297029703


100%|██████████| 152/152 [00:15<00:00,  9.61it/s]


epoch : 9 Accuracy : 0.62109375


 66%|██████▌   | 100/152 [00:10<00:05,  8.78it/s]

epoch : 10 batch : 100 loss : 0.7317283749580383
Accuracy : 0.8459158415841584


100%|██████████| 152/152 [00:16<00:00,  9.44it/s]


epoch : 10 Accuracy : 0.6171875


In [ ]:
def predict(model, text, text_pipeline):
    with torch.no_grad():
        text = torch.tensor(text_pipeline(text), dtype=torch.int64).to(device)
        text = text.unsqueeze(0)
        offsets = torch.tensor([0]).to(device)
        predicted_label = model(text, offsets)
        return predicted_label.argmax(1).item()

In [ ]:
# predict 함수 테스트
test_text = "아주 좋아요"
predicted_label = predict(MODEL, test_text, text_pipeline)
print(f"예측 : {predicted_label}")

ValueError: if input is 2D, then offsets has to be None, as input is treated is a mini-batch of fixed length sequences. However, found offsets of type <class 'torch.Tensor'>

In [ ]:
def predict(text):
    with torch.no_grad():
        label_text = ['두한', '정진영', '이정재', '이승만']
        text = torch.tensor(text_pipeline(text), dtype=torch.int64).to(device)
        text = text.unsqueeze(0)
        offsets = None
        print(text)
        predicted_label = MODEL(text, offsets)
        print(f"예측 : {label_text[predicted_label.argmax(1).item()]}")


predict("아주중요할때에신경쓰지도않았던작은일들이큰일을망치는경우를종종보았습니다.나머지는김고문이잘알아서하세요.") # 맞춤

tensor([[ 105, 5115,   79,    6,  689,    1,    1, 1647,   25,    4,    2,  516,
            3, 2429, 1257,    8, 2178,    1,    1, 1384,   10,  325,  279,    2,
            1,  378,    1]])
예측 : 이정재


In [ ]:
predict("친애하는국민여러분,저는대통령이승만입네다") # 틀림 

tensor([[816, 212, 202,   1,  38,  10, 229, 361, 765]])
예측 : 정진영


In [ ]:
predict("그래요?") # 맞춤

tensor([[503,   1]])
예측 : 이정재


In [ ]:
predict("이승만") # 틀림 

tensor([[361]])
예측 : 이정재


In [642]:
predict("이정치도썩고,사회도썩고이제학생들에게희망을가져봐야하지않겠습니까?어인사들해라.여기영태형님이시고,우리식구들신영균이,홍만길이,홍영철이.") # 맞춤

tensor([[   2,  242,   14, 4655,    1, 1023,   14, 4655,   73,  452,    4,   84,
         3650,    3, 1919,   89,    1,  512,    1,    1,  792,    4,   28,  166,
            1,   95,  283,  928,   81, 3396,    1,   19,  131,    4, 1099,    2,
            1, 3631,   60,  416,    1, 2245,    2,    1]])
예측 : 두한


In [645]:
predict("쩝,그거야뭐돈이생기면갚으면되는거지.아저…이거봐,우리저,나가자고어?저녁이나같이먹어.일환이도.어?") # 맞춤

tensor([[ 477,    1,  337,   30,    1,    2, 1795,  261, 3721,    1,    1,   15,
           38,    1,    2,   20,   89,    1,   19,   38,    1,    1,    1,  559,
          119,  239,  955,    1, 3410,    2,   14,    1,  100,    1]])
예측 : 두한


In [646]:
# 다른 사이트에서 대사 갖고오기: 베르길리우스 
# https://www.youtube.com/shorts/Q8pWmVp0v44
predict("회사는 자아실현의 공간이나 사상을 설파하는 장소가 아니다")

tensor([[5418,   10,    1,    1,   17,    1,  119, 1427,    3, 2085,    1, 1046,
            5, 1028]])
예측 : 이승만
